services:
  proxy:
    image: nginx:alpine
    container_name: proxy 
    ports: 
      - "80:80"
      # For https traffic but uneeded right now
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need ssl sertification
      # - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - basic-network

  api:
    build:
      context: ./nodeapp
      dockerfile: Dockerfile
    # Can't us container_name if using replicas
    # container_name: api
    # Use ports if it's just one, but if we're creating replicas then not neccessary
    # ports: 
    #   - "3000:3000"
    # Use this when you want to scale and have several services running
    deploy:
      mode: replicated
      replicas: 3 # Running 3 copies
      # You can setup environment variables here:
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/testdb
      - REDIS_URL=redis://cache:6379
    depends_on:
      - database
      - cache
    restart: unless-stopped
    networks:
      - basic-network

  database:
    image: postgres:15-alpine
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - basic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5d
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - basic-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # replication-databse
  # Used for making a read-only database: increases data integrity   

  # queue (Kafka | RabbitMQ | Dragonfly):
  # could add a queue container as well for long process or other needs
 
  # watcher:
  # add a monitoring tool

  # loki
  # for logs

  # watch-tower:
  # docker monitoring tool

  # secrets:
  # for managing secrets, env, and keys

  # grafana:
  # monitoring gui

  # prometheus:
  # metrics monitoring

  # PageDuty | Slack:
  # Alert Manager (possibly)

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

# Custom "simple" network
networks:
  basic-network:
    driver: bridge
