global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor node app
  - job_name: 'api'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:3000']
        labels:
          environment: 'production'
